export const PRODUCTS = [
    { id: 1, name: 'Zebronics Zeb-Thunder Pro Wireless Bluetooth', price: 299, image: 'https://shop.zebronics.com/cdn/shop/files/Zeb-Thunder-Pro-pic2.jpg?v=1709202990&width=700', category: 'tech' },
    { id: 2, name: 'Neon-G Shift Mouse', price: 89, image: 'https://gshiftlabs.com/wp-content/uploads/2022/08/gshift1.webp', category: 'gaming' },
    { id: 3, name: 'Cyber Mech Keyboard', price: 159, image: '/headphones.png', category: 'tech' },
    { id: 4, name: 'Z-Watch Ultra v2', price: 399, image: '/smartwatch.png', category: 'tech' },
    { id: 10, name: 'Pulse Smart Band', price: 129, image: 'https://www.gonoise.com/cdn/shop/products/NoisePulse1stImageNew_1.png?v=1655378598', category: 'tech' },
    { id: 5, name: 'Midnight Oversized Hoodie', price: 75, image: '/hoodie.png', category: 'apparel' },
    { id: 6, name: 'Z-Aura Tee', price: 35, image: '/hoodie.png', category: 'apparel' },
    { id: 7, name: 'Cyber Grip Pro Chair', price: 450, image: '/chair.png', category: 'gaming' },
    { id: 8, name: 'Neon Pulse Water Bottle', price: 25, image: '/hoodie.png', category: 'apparel' },
    { id: 11, name: 'Ghost Grip Sneakers', price: 180, image: '/sneakers.png', category: 'apparel' },
    { id: 12, name: 'Neon Step Runners', price: 210, image: '/sneakers.png', category: 'apparel' },
    { id: 13, name: 'Aura Flux Kicks', price: 195, image: '/sneakers.png', category: 'apparel' },
    { id: 14, name: 'Z-Desk Stealth', price: 599, image: '/chair.png', category: 'gaming' },
    { id: 15, name: 'RGB Throne v4', price: 650, image: '/chair.png', category: 'gaming' },
    { id: 16, name: 'Cyber Yellow Volts', price: 240, image: '/sneakers-yellow.png', category: 'apparel' },
    { id: 17, name: 'Hyper Pink Runners', price: 220, image: '/sneakers-pink.png', category: 'apparel' },
    { id: 18, name: 'Void Black Stealth', price: 260, image: '/sneakers-black.png', category: 'apparel' },
    { id: 19, name: 'Mech-X Gaming Mouse', price: 120, image: '/chair.png', category: 'gaming' },
    { id: 20, name: 'Orbit VR Headset', price: 899, image: '/headphones.png', category: 'tech' },
    { id: 10, name: "Nike Air Max Pulse", price: 160, image: "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?auto=format&fit=crop&q=80&w=400", category: "Apparel" },
    { id: 11, name: "Adidas Ultraboost Light", price: 190, image: "https://images.unsplash.com/photo-1587563877366-26417423bd84?auto=format&fit=crop&q=80&w=400", category: "Apparel" },
    { id: 12, name: "Z-PRO Oversized Hoodie", price: 85, image: "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&q=80&w=400", category: "Apparel" },
    { id: 13, name: "Mechanical Cyber Keyboard", price: 180, image: "https://images.unsplash.com/photo-1595225476474-87563907a212?auto=format&fit=crop&q=80&w=400", category: "Tech" },
    { id: 14, name: "Razer DeathAdder V3", price: 70, image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&q=80&w=400", category: "Gaming" }
];
